// File generated by FlutterFire CLI.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1opJWubwQoIPFwbOiy7oJj-dseTkU_Ws',
    appId: '1:637657171531:web:33455726333fd50855afce',
    messagingSenderId: '637657171531',
    projectId: 'solideremisr',
    authDomain: 'solideremisr.firebaseapp.com',
    storageBucket: 'solideremisr.firebasestorage.app',
    measurementId: 'G-50KSRQYFKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuADlIhWXTrAm7HUC1SDLUpLUwFnrh4I',
    appId: '1:637657171531:android:79ef8eacabd6138455afce',
    messagingSenderId: '637657171531',
    projectId: 'solideremisr',
    storageBucket: 'solideremisr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYAZlG9gBKRvP4mlXtLcPqtkR2SWktvNw',
    appId: '1:637657171531:ios:9e8d92b36a4a05ac55afce',
    messagingSenderId: '637657171531',
    projectId: 'solideremisr',
    storageBucket: 'solideremisr.firebasestorage.app',
    iosBundleId: 'com.example.solidereMisr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYAZlG9gBKRvP4mlXtLcPqtkR2SWktvNw',
    appId: '1:637657171531:ios:9e8d92b36a4a05ac55afce',
    messagingSenderId: '637657171531',
    projectId: 'solideremisr',
    storageBucket: 'solideremisr.firebasestorage.app',
    iosBundleId: 'com.example.solidereMisr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1opJWubwQoIPFwbOiy7oJj-dseTkU_Ws',
    appId: '1:637657171531:web:29917e53001f5dc055afce',
    messagingSenderId: '637657171531',
    projectId: 'solideremisr',
    authDomain: 'solideremisr.firebaseapp.com',
    storageBucket: 'solideremisr.firebasestorage.app',
    measurementId: 'G-E0KJWSCEF2',
  );
}
